name: Test on Commit to Dev

on:
  push:
    branches:
      - dev

jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your application testing steps here

  test_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # Add any other Terraform testing steps you'd like to perform

  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev to testing"
          title: "Merge dev to testing"
          body: "Automated PR to update testing branch with latest changes from dev"
          branch: "auto-merge-dev-to-testing"
          base: "testing"
